Application/config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  resources :rooms, only: [:index, :show]
  resources :messages, only: [:create]
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

end

Application/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, :all
    can :manage, Message, user_id: user.id
    can :manage, User, id: user.id
    if user.admin?
        can :manage, :all
    end
  end
end

Application/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
  validates :body, :user, presence: true
  default_scope -> { order('created_at ASC') }
end

Application/app/models/room.rb
class Room < ActiveRecord::Base
  validates :name, :owner, presence: true
  belongs_to :owner, class_name: User, foreign_key: :user_id
  has_many :messages, dependent: :destroy

  def users_online
    user_rooms = $redis.get('user_rooms').presence
    user_rooms = user_rooms ? Marshal.load(user_rooms) : {}
    user_ids   = user_rooms.select{ |k, v| v.include?(self.id) }.keys
    User.where(id: user_ids)
  end
end

Application/app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w{student teacher admin}.freeze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :name, presence: true
  validates :role, inclusion: { in: ROLES }

  ROLES.each do |role_name|
    define_method("#{role_name}?") do
      role_name.to_s == role.to_s
    end

    scope role_name.pluralize, -> { User.where(role: role_name) }
  end

  def in_rooms
    room_ids = $redis.get('user_rooms').presence
    room_ids = room_ids ? Marshal.load(room_ids)[self.id] : []
    Room.where(id: room_ids)
  end

  def join_room(room)
    user_rooms = $redis.get('user_rooms').presence
    user_rooms = user_rooms ? Marshal.load(user_rooms) : {}
    user_rooms[self.id] ||= []
    user_rooms[self.id].push(room.id).uniq!
    user_rooms = Marshal.dump(user_rooms)
    $redis.set("user_rooms", user_rooms)
  end

  def leave_room(room)
    user_rooms = $redis.get('user_rooms').presence
    user_rooms = user_rooms ? Marshal.load(user_rooms) : {}
    user_rooms[self.id] ||= []
    user_rooms[self.id] = user_rooms[self.id] - [room.id]
    user_rooms = Marshal.dump(user_rooms)
    $redis.set("user_rooms", user_rooms)
  end
end

Application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Application/app/controllers/chat_controller.rb
# class ChatController < FayeRails::Controller
#   channel '/messages' do
#     subscribe do
#       Rails.logger.debug "Received on #{channel}: #{inspect}"

#       created_at = if message['created_at'].present?
#                      Time.parse(message['created_at'])
#                    else
#                      Time.now
#                    end

#      # Message.create(message: message['message'], created_at: created_at)
#     end
#   end
# end

Application/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :message
  before_action :set_message, only: [:show]

  # GET /messages
  def index
    @messages = Message.all
  end

  # GET /messages/1
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
    @message = current_user.messages.find(params[:id])
  end

  # POST /messages
  def create
    @message = current_user.messages.new(message_params)
    @room = Room.find(params[:message][:room_id])
    if @message.save
    else
    end

    # if @message.save
    #   redirect_to @room, notice: 'Message was successfully created.'
    # else
    #   render :new
    # end
  end

  # PATCH/PUT /messages/1
  def update
    @message = current_user.messages.find(params[:id])
    if @message.update(message_params)
      redirect_to @message, notice: 'Message was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /messages/1
  def destroy
    @message = current_user.messages.find(params[:id])
    @message.destroy
    redirect_to :back, notice: 'Message was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:room_id, :body)
    end
end

Application/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :room
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  def show
    current_user.join_room(@room)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def room_params
      params.require(:room).permit(:name, :user_id)
    end
end

Application/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :user
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name)
    end
end

Application/app/helpers/application_helper.rb
module ApplicationHelper
end

Application/app/helpers/messages_helper.rb
module MessagesHelper
end

Application/app/helpers/rooms_helper.rb
module RoomsHelper
end

Application/app/helpers/users_helper.rb
module UsersHelper
end

Application/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title znOnline
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to t('project_name'), root_path, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to t('users'), users_path
            %li= link_to t('rooms'), rooms_path
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li= link_to "Profile", edit_user_path(current_user)
              %li= link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li= link_to "Sign up", new_user_registration_path
              %li= link_to "Sign in", new_user_session_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

Application/app/views/messages/_form.html.haml
= form_for message, html: { class: "form-horizontal", role: "form" }, format: :js, remote: true do |f|
  -if message.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(message.errors.count, "error")} prohibited this message from being saved:"

      %ul
        - message.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :body, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :body, class: 'form-control'
      = f.hidden_field :room_id, value: room.id if local_assigns[:room]
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

Application/app/views/messages/_message.html.haml
.well.well-sm
  = message.user.name
  .pull-right
    = message.created_at.strftime("%e %b, %X")
  %br/
  = message.body

Application/app/views/messages/create.js.erb
publisher = client.publish('/messages', {
  message: '<%= j render @message, locals: { message: @message } %>'
});

publisher.callback(function() {
  $('#message_body').val('');
  $('#new_message').find("input[type='submit']").val('Submit').prop('disabled', false)
});

publisher.errback(function() {
  alert('There was an error while posting your message.');
});

Application/app/views/rooms/_room.html.haml
%tr
  %td= link_to room.name, room_path(room)
  %td= room.users_online.count
  %td= room.owner.name

Application/app/views/rooms/index.html.haml
.page-header
  %h1= t("activerecord.models.room")

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t("activerecord.attributes.room.name")
        %th= t("activerecord.attributes.room.users_online")
        %th= t("activerecord.attributes.room.owner_name")


    %tbody
      = render @rooms

Application/app/views/rooms/show.html.haml
.page-header
  = link_to rooms_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1= @room.name

.row
  .col-sm-3
    %h2= @room.owner.name
    %video#vid
    %ul
      - @room.users_online.each do |user|
        %li= link_to user.name, user_path(user)
  .col-sm-9
    #messages
      .media-list= render @room.messages
    %hr/
    = render 'messages/form', message: Message.new, room: @room

Application/app/views/users/_form.html.haml
= form_for @user, html: { class: "form-horizontal", role: "form" } do |f|
  -if @user.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@user.errors.count, "error")} prohibited this @user from being saved:"

      %ul
        - @user.errors.full_@users.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :name, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

Application/app/views/users/_user.html.haml
%tr
  %td= link_to user.name, user_path(user)
  %td= t("roles.#{user.role}")
  %td= user.messages.count

Application/app/views/users/edit.html.haml
%h1 Profile

= render 'form'

Application/app/views/users/index.html.haml
%h1 Users

%table.table.table-bordered.table-hover.table-striped
  %thead
    %tr
      %th Name
      %th Role
      %th Messages

  %tbody
    = render @users

Application/app/views/users/show.html.haml
%p
  %b Name:
  = @user.name

= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' if can?(:manage, @user)

= link_to 'Back', users_path, class: 'btn btn-default'